/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as appTourOperatorsTourOperatorIdRouteRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/route'
import { Route as appTourOperatorsNewRouteImport } from './routes/(app)/tour-operators/new'
import { Route as appTourOperatorsTourOperatorIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/index'
import { Route as appTourOperatorsTourOperatorIdActivityIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/activity/index'
import { Route as appTourOperatorsTourOperatorIdAudiencesIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/audiences/index'
import { Route as appTourOperatorsTourOperatorIdAudiencesNewRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/audiences/new'
import { Route as appTourOperatorsTourOperatorIdAvailabilityIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/availability/index'
import { Route as appTourOperatorsTourOperatorIdExperiencesIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/index'
import { Route as appTourOperatorsTourOperatorIdExperiencesNewRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/new'
import { Route as appTourOperatorsTourOperatorIdPickupLocationsIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/pickup-locations/index'
import { Route as appTourOperatorsTourOperatorIdPickupLocationsNewRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/pickup-locations/new'
import { Route as appTourOperatorsTourOperatorIdSettingsIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/index'
import { Route as appTourOperatorsTourOperatorIdActivityEntryIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/activity/$entryId/index'
import { Route as appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/index'
import { Route as appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
import { Route as appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
import { Route as appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/availability/$slotId/index'
import { Route as appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/availability/new/$experienceId'
import { Route as appTourOperatorsTourOperatorIdContentMediaIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/content/media/index'
import { Route as appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
import { Route as appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/index'
import { Route as appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
import { Route as appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
import { Route as appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/index'
import { Route as appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
import { Route as appTourOperatorsTourOperatorIdSettingsAccountIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/account/index'
import { Route as appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/general/index'
import { Route as appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/invitations/index'
import { Route as appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
import { Route as appTourOperatorsTourOperatorIdSettingsLanguagesIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/languages/index'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/index'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/new'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const appTourOperatorsTourOperatorIdRouteRoute =
  appTourOperatorsTourOperatorIdRouteRouteImport.update({
    id: '/tour-operators/$tourOperatorId',
    path: '/tour-operators/$tourOperatorId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appTourOperatorsNewRoute = appTourOperatorsNewRouteImport.update({
  id: '/tour-operators/new',
  path: '/tour-operators/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appTourOperatorsTourOperatorIdIndexRoute =
  appTourOperatorsTourOperatorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdActivityIndexRoute =
  appTourOperatorsTourOperatorIdActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAudiencesIndexRoute =
  appTourOperatorsTourOperatorIdAudiencesIndexRouteImport.update({
    id: '/audiences/',
    path: '/audiences/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAudiencesNewRoute =
  appTourOperatorsTourOperatorIdAudiencesNewRouteImport.update({
    id: '/audiences/new',
    path: '/audiences/new',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAvailabilityIndexRoute =
  appTourOperatorsTourOperatorIdAvailabilityIndexRouteImport.update({
    id: '/availability/',
    path: '/availability/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesIndexRoute =
  appTourOperatorsTourOperatorIdExperiencesIndexRouteImport.update({
    id: '/experiences/',
    path: '/experiences/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesNewRoute =
  appTourOperatorsTourOperatorIdExperiencesNewRouteImport.update({
    id: '/experiences/new',
    path: '/experiences/new',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdPickupLocationsIndexRoute =
  appTourOperatorsTourOperatorIdPickupLocationsIndexRouteImport.update({
    id: '/pickup-locations/',
    path: '/pickup-locations/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdPickupLocationsNewRoute =
  appTourOperatorsTourOperatorIdPickupLocationsNewRouteImport.update({
    id: '/pickup-locations/new',
    path: '/pickup-locations/new',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsIndexRoute =
  appTourOperatorsTourOperatorIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute =
  appTourOperatorsTourOperatorIdActivityEntryIdIndexRouteImport.update({
    id: '/activity/$entryId/',
    path: '/activity/$entryId/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute =
  appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRouteImport.update({
    id: '/audiences/$audienceId/',
    path: '/audiences/$audienceId/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute =
  appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRouteImport.update({
    id: '/audiences/$audienceId/edit',
    path: '/audiences/$audienceId/edit',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute =
  appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRouteImport.update(
    {
      id: '/audiences/$audienceId/translations',
      path: '/audiences/$audienceId/translations',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute =
  appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRouteImport.update({
    id: '/availability/$slotId/',
    path: '/availability/$slotId/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute =
  appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRouteImport.update({
    id: '/availability/new/$experienceId',
    path: '/availability/new/$experienceId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdContentMediaIndexRoute =
  appTourOperatorsTourOperatorIdContentMediaIndexRouteImport.update({
    id: '/content/media/',
    path: '/content/media/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdContentMediaMediaIdRoute =
  appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport.update({
    id: '/content/media/$mediaId',
    path: '/content/media/$mediaId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute =
  appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRouteImport.update({
    id: '/experiences/$experienceId/',
    path: '/experiences/$experienceId/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute =
  appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRouteImport.update({
    id: '/experiences/$experienceId/edit',
    path: '/experiences/$experienceId/edit',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute =
  appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRouteImport.update(
    {
      id: '/experiences/$experienceId/translations',
      path: '/experiences/$experienceId/translations',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute =
  appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRouteImport.update(
    {
      id: '/pickup-locations/$pickupLocationId/',
      path: '/pickup-locations/$pickupLocationId/',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute =
  appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRouteImport.update(
    {
      id: '/pickup-locations/$pickupLocationId/edit',
      path: '/pickup-locations/$pickupLocationId/edit',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdSettingsAccountIndexRoute =
  appTourOperatorsTourOperatorIdSettingsAccountIndexRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute =
  appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport.update({
    id: '/settings/general/',
    path: '/settings/general/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute =
  appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport.update({
    id: '/settings/invitations/',
    path: '/settings/invitations/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute =
  appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport.update(
    {
      id: '/settings/invitations/$invitationId',
      path: '/settings/invitations/$invitationId',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute =
  appTourOperatorsTourOperatorIdSettingsLanguagesIndexRouteImport.update({
    id: '/settings/languages/',
    path: '/settings/languages/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsMembersIndexRoute =
  appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute =
  appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport.update({
    id: '/settings/members/$userId',
    path: '/settings/members/$userId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsMembersNewRoute =
  appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport.update({
    id: '/settings/members/new',
    path: '/settings/members/new',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof appIndexRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/tour-operators/$tourOperatorId/audiences/new': typeof appTourOperatorsTourOperatorIdAudiencesNewRoute
  '/tour-operators/$tourOperatorId/experiences/new': typeof appTourOperatorsTourOperatorIdExperiencesNewRoute
  '/tour-operators/$tourOperatorId/pickup-locations/new': typeof appTourOperatorsTourOperatorIdPickupLocationsNewRoute
  '/tour-operators/$tourOperatorId/activity/': typeof appTourOperatorsTourOperatorIdActivityIndexRoute
  '/tour-operators/$tourOperatorId/audiences/': typeof appTourOperatorsTourOperatorIdAudiencesIndexRoute
  '/tour-operators/$tourOperatorId/availability/': typeof appTourOperatorsTourOperatorIdAvailabilityIndexRoute
  '/tour-operators/$tourOperatorId/experiences/': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/tour-operators/$tourOperatorId/pickup-locations/': typeof appTourOperatorsTourOperatorIdPickupLocationsIndexRoute
  '/tour-operators/$tourOperatorId/settings/': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId/edit': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId/translations': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute
  '/tour-operators/$tourOperatorId/availability/new/$experienceId': typeof appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute
  '/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId/edit': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId/translations': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute
  '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute
  '/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/tour-operators/$tourOperatorId/activity/$entryId/': typeof appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId/': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute
  '/tour-operators/$tourOperatorId/availability/$slotId/': typeof appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute
  '/tour-operators/$tourOperatorId/content/media/': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId/': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute
  '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute
  '/tour-operators/$tourOperatorId/settings/account/': typeof appTourOperatorsTourOperatorIdSettingsAccountIndexRoute
  '/tour-operators/$tourOperatorId/settings/general/': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/tour-operators/$tourOperatorId/settings/invitations/': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/tour-operators/$tourOperatorId/settings/languages/': typeof appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute
  '/tour-operators/$tourOperatorId/settings/members/': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof appIndexRoute
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/tour-operators/$tourOperatorId/audiences/new': typeof appTourOperatorsTourOperatorIdAudiencesNewRoute
  '/tour-operators/$tourOperatorId/experiences/new': typeof appTourOperatorsTourOperatorIdExperiencesNewRoute
  '/tour-operators/$tourOperatorId/pickup-locations/new': typeof appTourOperatorsTourOperatorIdPickupLocationsNewRoute
  '/tour-operators/$tourOperatorId/activity': typeof appTourOperatorsTourOperatorIdActivityIndexRoute
  '/tour-operators/$tourOperatorId/audiences': typeof appTourOperatorsTourOperatorIdAudiencesIndexRoute
  '/tour-operators/$tourOperatorId/availability': typeof appTourOperatorsTourOperatorIdAvailabilityIndexRoute
  '/tour-operators/$tourOperatorId/experiences': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/tour-operators/$tourOperatorId/pickup-locations': typeof appTourOperatorsTourOperatorIdPickupLocationsIndexRoute
  '/tour-operators/$tourOperatorId/settings': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId/edit': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId/translations': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute
  '/tour-operators/$tourOperatorId/availability/new/$experienceId': typeof appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute
  '/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId/edit': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId/translations': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute
  '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute
  '/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/tour-operators/$tourOperatorId/activity/$entryId': typeof appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute
  '/tour-operators/$tourOperatorId/audiences/$audienceId': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute
  '/tour-operators/$tourOperatorId/availability/$slotId': typeof appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute
  '/tour-operators/$tourOperatorId/content/media': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute
  '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute
  '/tour-operators/$tourOperatorId/settings/account': typeof appTourOperatorsTourOperatorIdSettingsAccountIndexRoute
  '/tour-operators/$tourOperatorId/settings/general': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/tour-operators/$tourOperatorId/settings/invitations': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/tour-operators/$tourOperatorId/settings/languages': typeof appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute
  '/tour-operators/$tourOperatorId/settings/members': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/(app)/tour-operators/new': typeof appTourOperatorsNewRoute
  '/(app)/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/audiences/new': typeof appTourOperatorsTourOperatorIdAudiencesNewRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/new': typeof appTourOperatorsTourOperatorIdExperiencesNewRoute
  '/(app)/tour-operators/$tourOperatorId/pickup-locations/new': typeof appTourOperatorsTourOperatorIdPickupLocationsNewRoute
  '/(app)/tour-operators/$tourOperatorId/activity/': typeof appTourOperatorsTourOperatorIdActivityIndexRoute
  '/(app)/tour-operators/$tourOperatorId/audiences/': typeof appTourOperatorsTourOperatorIdAudiencesIndexRoute
  '/(app)/tour-operators/$tourOperatorId/availability/': typeof appTourOperatorsTourOperatorIdAvailabilityIndexRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/(app)/tour-operators/$tourOperatorId/pickup-locations/': typeof appTourOperatorsTourOperatorIdPickupLocationsIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/edit': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute
  '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/translations': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute
  '/(app)/tour-operators/$tourOperatorId/availability/new/$experienceId': typeof appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute
  '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/edit': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/translations': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute
  '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute
  '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/(app)/tour-operators/$tourOperatorId/activity/$entryId/': typeof appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/': typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/availability/$slotId/': typeof appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/content/media/': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/': typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/account/': typeof appTourOperatorsTourOperatorIdSettingsAccountIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/general/': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/invitations/': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/languages/': typeof appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/invitations/accept'
    | '/'
    | '/tour-operators/$tourOperatorId'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId/'
    | '/tour-operators/$tourOperatorId/audiences/new'
    | '/tour-operators/$tourOperatorId/experiences/new'
    | '/tour-operators/$tourOperatorId/pickup-locations/new'
    | '/tour-operators/$tourOperatorId/activity/'
    | '/tour-operators/$tourOperatorId/audiences/'
    | '/tour-operators/$tourOperatorId/availability/'
    | '/tour-operators/$tourOperatorId/experiences/'
    | '/tour-operators/$tourOperatorId/pickup-locations/'
    | '/tour-operators/$tourOperatorId/settings/'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
    | '/tour-operators/$tourOperatorId/availability/new/$experienceId'
    | '/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
    | '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
    | '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/tour-operators/$tourOperatorId/settings/members/new'
    | '/tour-operators/$tourOperatorId/activity/$entryId/'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId/'
    | '/tour-operators/$tourOperatorId/availability/$slotId/'
    | '/tour-operators/$tourOperatorId/content/media/'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId/'
    | '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/'
    | '/tour-operators/$tourOperatorId/settings/account/'
    | '/tour-operators/$tourOperatorId/settings/general/'
    | '/tour-operators/$tourOperatorId/settings/invitations/'
    | '/tour-operators/$tourOperatorId/settings/languages/'
    | '/tour-operators/$tourOperatorId/settings/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/invitations/accept'
    | '/'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId'
    | '/tour-operators/$tourOperatorId/audiences/new'
    | '/tour-operators/$tourOperatorId/experiences/new'
    | '/tour-operators/$tourOperatorId/pickup-locations/new'
    | '/tour-operators/$tourOperatorId/activity'
    | '/tour-operators/$tourOperatorId/audiences'
    | '/tour-operators/$tourOperatorId/availability'
    | '/tour-operators/$tourOperatorId/experiences'
    | '/tour-operators/$tourOperatorId/pickup-locations'
    | '/tour-operators/$tourOperatorId/settings'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
    | '/tour-operators/$tourOperatorId/availability/new/$experienceId'
    | '/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
    | '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
    | '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/tour-operators/$tourOperatorId/settings/members/new'
    | '/tour-operators/$tourOperatorId/activity/$entryId'
    | '/tour-operators/$tourOperatorId/audiences/$audienceId'
    | '/tour-operators/$tourOperatorId/availability/$slotId'
    | '/tour-operators/$tourOperatorId/content/media'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId'
    | '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId'
    | '/tour-operators/$tourOperatorId/settings/account'
    | '/tour-operators/$tourOperatorId/settings/general'
    | '/tour-operators/$tourOperatorId/settings/invitations'
    | '/tour-operators/$tourOperatorId/settings/languages'
    | '/tour-operators/$tourOperatorId/settings/members'
  id:
    | '__root__'
    | '/(app)'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/auth/verify-email'
    | '/invitations/accept'
    | '/(app)/'
    | '/(app)/tour-operators/$tourOperatorId'
    | '/(app)/tour-operators/new'
    | '/(app)/tour-operators/$tourOperatorId/'
    | '/(app)/tour-operators/$tourOperatorId/audiences/new'
    | '/(app)/tour-operators/$tourOperatorId/experiences/new'
    | '/(app)/tour-operators/$tourOperatorId/pickup-locations/new'
    | '/(app)/tour-operators/$tourOperatorId/activity/'
    | '/(app)/tour-operators/$tourOperatorId/audiences/'
    | '/(app)/tour-operators/$tourOperatorId/availability/'
    | '/(app)/tour-operators/$tourOperatorId/experiences/'
    | '/(app)/tour-operators/$tourOperatorId/pickup-locations/'
    | '/(app)/tour-operators/$tourOperatorId/settings/'
    | '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
    | '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
    | '/(app)/tour-operators/$tourOperatorId/availability/new/$experienceId'
    | '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
    | '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
    | '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
    | '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/new'
    | '/(app)/tour-operators/$tourOperatorId/activity/$entryId/'
    | '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/'
    | '/(app)/tour-operators/$tourOperatorId/availability/$slotId/'
    | '/(app)/tour-operators/$tourOperatorId/content/media/'
    | '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/'
    | '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/'
    | '/(app)/tour-operators/$tourOperatorId/settings/account/'
    | '/(app)/tour-operators/$tourOperatorId/settings/general/'
    | '/(app)/tour-operators/$tourOperatorId/settings/invitations/'
    | '/(app)/tour-operators/$tourOperatorId/settings/languages/'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/tour-operators/$tourOperatorId': {
      id: '/(app)/tour-operators/$tourOperatorId'
      path: '/tour-operators/$tourOperatorId'
      fullPath: '/tour-operators/$tourOperatorId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/new': {
      id: '/(app)/tour-operators/new'
      path: '/tour-operators/new'
      fullPath: '/tour-operators/new'
      preLoaderRoute: typeof appTourOperatorsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/': {
      id: '/(app)/tour-operators/$tourOperatorId/'
      path: '/'
      fullPath: '/tour-operators/$tourOperatorId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/activity/': {
      id: '/(app)/tour-operators/$tourOperatorId/activity/'
      path: '/activity'
      fullPath: '/tour-operators/$tourOperatorId/activity/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdActivityIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/audiences/': {
      id: '/(app)/tour-operators/$tourOperatorId/audiences/'
      path: '/audiences'
      fullPath: '/tour-operators/$tourOperatorId/audiences/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAudiencesIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/audiences/new': {
      id: '/(app)/tour-operators/$tourOperatorId/audiences/new'
      path: '/audiences/new'
      fullPath: '/tour-operators/$tourOperatorId/audiences/new'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAudiencesNewRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/availability/': {
      id: '/(app)/tour-operators/$tourOperatorId/availability/'
      path: '/availability'
      fullPath: '/tour-operators/$tourOperatorId/availability/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAvailabilityIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/'
      path: '/experiences'
      fullPath: '/tour-operators/$tourOperatorId/experiences/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/new': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/new'
      path: '/experiences/new'
      fullPath: '/tour-operators/$tourOperatorId/experiences/new'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesNewRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/pickup-locations/': {
      id: '/(app)/tour-operators/$tourOperatorId/pickup-locations/'
      path: '/pickup-locations'
      fullPath: '/tour-operators/$tourOperatorId/pickup-locations/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/pickup-locations/new': {
      id: '/(app)/tour-operators/$tourOperatorId/pickup-locations/new'
      path: '/pickup-locations/new'
      fullPath: '/tour-operators/$tourOperatorId/pickup-locations/new'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsNewRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/'
      path: '/settings'
      fullPath: '/tour-operators/$tourOperatorId/settings/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/activity/$entryId/': {
      id: '/(app)/tour-operators/$tourOperatorId/activity/$entryId/'
      path: '/activity/$entryId'
      fullPath: '/tour-operators/$tourOperatorId/activity/$entryId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdActivityEntryIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/': {
      id: '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/'
      path: '/audiences/$audienceId'
      fullPath: '/tour-operators/$tourOperatorId/audiences/$audienceId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/edit': {
      id: '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
      path: '/audiences/$audienceId/edit'
      fullPath: '/tour-operators/$tourOperatorId/audiences/$audienceId/edit'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/translations': {
      id: '/(app)/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
      path: '/audiences/$audienceId/translations'
      fullPath: '/tour-operators/$tourOperatorId/audiences/$audienceId/translations'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/availability/$slotId/': {
      id: '/(app)/tour-operators/$tourOperatorId/availability/$slotId/'
      path: '/availability/$slotId'
      fullPath: '/tour-operators/$tourOperatorId/availability/$slotId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/availability/new/$experienceId': {
      id: '/(app)/tour-operators/$tourOperatorId/availability/new/$experienceId'
      path: '/availability/new/$experienceId'
      fullPath: '/tour-operators/$tourOperatorId/availability/new/$experienceId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/content/media/': {
      id: '/(app)/tour-operators/$tourOperatorId/content/media/'
      path: '/content/media'
      fullPath: '/tour-operators/$tourOperatorId/content/media/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdContentMediaIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId': {
      id: '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
      path: '/content/media/$mediaId'
      fullPath: '/tour-operators/$tourOperatorId/content/media/$mediaId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/'
      path: '/experiences/$experienceId'
      fullPath: '/tour-operators/$tourOperatorId/experiences/$experienceId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/edit': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
      path: '/experiences/$experienceId/edit'
      fullPath: '/tour-operators/$tourOperatorId/experiences/$experienceId/edit'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/translations': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
      path: '/experiences/$experienceId/translations'
      fullPath: '/tour-operators/$tourOperatorId/experiences/$experienceId/translations'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/': {
      id: '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/'
      path: '/pickup-locations/$pickupLocationId'
      fullPath: '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit': {
      id: '/(app)/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
      path: '/pickup-locations/$pickupLocationId/edit'
      fullPath: '/tour-operators/$tourOperatorId/pickup-locations/$pickupLocationId/edit'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/account/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/account/'
      path: '/settings/account'
      fullPath: '/tour-operators/$tourOperatorId/settings/account/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsAccountIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/general/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/general/'
      path: '/settings/general'
      fullPath: '/tour-operators/$tourOperatorId/settings/general/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/invitations/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/invitations/'
      path: '/settings/invitations'
      fullPath: '/tour-operators/$tourOperatorId/settings/invitations/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
      path: '/settings/invitations/$invitationId'
      fullPath: '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/languages/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/languages/'
      path: '/settings/languages'
      fullPath: '/tour-operators/$tourOperatorId/settings/languages/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsLanguagesIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/'
      path: '/settings/members'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/$userId': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
      path: '/settings/members/$userId'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/$userId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/new': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/new'
      path: '/settings/members/new'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/new'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
  }
}

interface appTourOperatorsTourOperatorIdRouteRouteChildren {
  appTourOperatorsTourOperatorIdIndexRoute: typeof appTourOperatorsTourOperatorIdIndexRoute
  appTourOperatorsTourOperatorIdAudiencesNewRoute: typeof appTourOperatorsTourOperatorIdAudiencesNewRoute
  appTourOperatorsTourOperatorIdExperiencesNewRoute: typeof appTourOperatorsTourOperatorIdExperiencesNewRoute
  appTourOperatorsTourOperatorIdPickupLocationsNewRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsNewRoute
  appTourOperatorsTourOperatorIdActivityIndexRoute: typeof appTourOperatorsTourOperatorIdActivityIndexRoute
  appTourOperatorsTourOperatorIdAudiencesIndexRoute: typeof appTourOperatorsTourOperatorIdAudiencesIndexRoute
  appTourOperatorsTourOperatorIdAvailabilityIndexRoute: typeof appTourOperatorsTourOperatorIdAvailabilityIndexRoute
  appTourOperatorsTourOperatorIdExperiencesIndexRoute: typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  appTourOperatorsTourOperatorIdPickupLocationsIndexRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsIndexRoute
  appTourOperatorsTourOperatorIdSettingsIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute
  appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute
  appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute: typeof appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute
  appTourOperatorsTourOperatorIdContentMediaMediaIdRoute: typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute
  appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute
  appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute
  appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  appTourOperatorsTourOperatorIdSettingsMembersNewRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute: typeof appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute
  appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute: typeof appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute
  appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute: typeof appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute
  appTourOperatorsTourOperatorIdContentMediaIndexRoute: typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute
  appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute: typeof appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute
  appTourOperatorsTourOperatorIdSettingsAccountIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsAccountIndexRoute
  appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute
  appTourOperatorsTourOperatorIdSettingsMembersIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}

const appTourOperatorsTourOperatorIdRouteRouteChildren: appTourOperatorsTourOperatorIdRouteRouteChildren =
  {
    appTourOperatorsTourOperatorIdIndexRoute:
      appTourOperatorsTourOperatorIdIndexRoute,
    appTourOperatorsTourOperatorIdAudiencesNewRoute:
      appTourOperatorsTourOperatorIdAudiencesNewRoute,
    appTourOperatorsTourOperatorIdExperiencesNewRoute:
      appTourOperatorsTourOperatorIdExperiencesNewRoute,
    appTourOperatorsTourOperatorIdPickupLocationsNewRoute:
      appTourOperatorsTourOperatorIdPickupLocationsNewRoute,
    appTourOperatorsTourOperatorIdActivityIndexRoute:
      appTourOperatorsTourOperatorIdActivityIndexRoute,
    appTourOperatorsTourOperatorIdAudiencesIndexRoute:
      appTourOperatorsTourOperatorIdAudiencesIndexRoute,
    appTourOperatorsTourOperatorIdAvailabilityIndexRoute:
      appTourOperatorsTourOperatorIdAvailabilityIndexRoute,
    appTourOperatorsTourOperatorIdExperiencesIndexRoute:
      appTourOperatorsTourOperatorIdExperiencesIndexRoute,
    appTourOperatorsTourOperatorIdPickupLocationsIndexRoute:
      appTourOperatorsTourOperatorIdPickupLocationsIndexRoute,
    appTourOperatorsTourOperatorIdSettingsIndexRoute:
      appTourOperatorsTourOperatorIdSettingsIndexRoute,
    appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute:
      appTourOperatorsTourOperatorIdAudiencesAudienceIdEditRoute,
    appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute:
      appTourOperatorsTourOperatorIdAudiencesAudienceIdTranslationsRoute,
    appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute:
      appTourOperatorsTourOperatorIdAvailabilityNewExperienceIdRoute,
    appTourOperatorsTourOperatorIdContentMediaMediaIdRoute:
      appTourOperatorsTourOperatorIdContentMediaMediaIdRoute,
    appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute:
      appTourOperatorsTourOperatorIdExperiencesExperienceIdEditRoute,
    appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute:
      appTourOperatorsTourOperatorIdExperiencesExperienceIdTranslationsRoute,
    appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute:
      appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdEditRoute,
    appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute:
      appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute,
    appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute:
      appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute,
    appTourOperatorsTourOperatorIdSettingsMembersNewRoute:
      appTourOperatorsTourOperatorIdSettingsMembersNewRoute,
    appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute:
      appTourOperatorsTourOperatorIdActivityEntryIdIndexRoute,
    appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute:
      appTourOperatorsTourOperatorIdAudiencesAudienceIdIndexRoute,
    appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute:
      appTourOperatorsTourOperatorIdAvailabilitySlotIdIndexRoute,
    appTourOperatorsTourOperatorIdContentMediaIndexRoute:
      appTourOperatorsTourOperatorIdContentMediaIndexRoute,
    appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute:
      appTourOperatorsTourOperatorIdExperiencesExperienceIdIndexRoute,
    appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute:
      appTourOperatorsTourOperatorIdPickupLocationsPickupLocationIdIndexRoute,
    appTourOperatorsTourOperatorIdSettingsAccountIndexRoute:
      appTourOperatorsTourOperatorIdSettingsAccountIndexRoute,
    appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute:
      appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute,
    appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute:
      appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute,
    appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute:
      appTourOperatorsTourOperatorIdSettingsLanguagesIndexRoute,
    appTourOperatorsTourOperatorIdSettingsMembersIndexRoute:
      appTourOperatorsTourOperatorIdSettingsMembersIndexRoute,
  }

const appTourOperatorsTourOperatorIdRouteRouteWithChildren =
  appTourOperatorsTourOperatorIdRouteRoute._addFileChildren(
    appTourOperatorsTourOperatorIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appTourOperatorsTourOperatorIdRouteRoute: typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  appTourOperatorsNewRoute: typeof appTourOperatorsNewRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appTourOperatorsTourOperatorIdRouteRoute:
    appTourOperatorsTourOperatorIdRouteRouteWithChildren,
  appTourOperatorsNewRoute: appTourOperatorsNewRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
