/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as appTourOperatorsTourOperatorIdRouteRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/route'
import { Route as appTourOperatorsNewRouteImport } from './routes/(app)/tour-operators/new'
import { Route as appTourOperatorsTourOperatorIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appTourOperatorsTourOperatorIdRouteRoute =
  appTourOperatorsTourOperatorIdRouteRouteImport.update({
    id: '/tour-operators/$tourOperatorId',
    path: '/tour-operators/$tourOperatorId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appTourOperatorsNewRoute = appTourOperatorsNewRouteImport.update({
  id: '/tour-operators/new',
  path: '/tour-operators/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appTourOperatorsTourOperatorIdIndexRoute =
  appTourOperatorsTourOperatorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof appIndexRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof appIndexRoute
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/(app)/tour-operators/new': typeof appTourOperatorsNewRoute
  '/(app)/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/tour-operators/$tourOperatorId'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId'
  id:
    | '__root__'
    | '/(app)'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/(app)/'
    | '/(app)/tour-operators/$tourOperatorId'
    | '/(app)/tour-operators/new'
    | '/(app)/tour-operators/$tourOperatorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId': {
      id: '/(app)/tour-operators/$tourOperatorId'
      path: '/tour-operators/$tourOperatorId'
      fullPath: '/tour-operators/$tourOperatorId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/new': {
      id: '/(app)/tour-operators/new'
      path: '/tour-operators/new'
      fullPath: '/tour-operators/new'
      preLoaderRoute: typeof appTourOperatorsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/': {
      id: '/(app)/tour-operators/$tourOperatorId/'
      path: '/'
      fullPath: '/tour-operators/$tourOperatorId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
  }
}

interface appTourOperatorsTourOperatorIdRouteRouteChildren {
  appTourOperatorsTourOperatorIdIndexRoute: typeof appTourOperatorsTourOperatorIdIndexRoute
}

const appTourOperatorsTourOperatorIdRouteRouteChildren: appTourOperatorsTourOperatorIdRouteRouteChildren =
  {
    appTourOperatorsTourOperatorIdIndexRoute:
      appTourOperatorsTourOperatorIdIndexRoute,
  }

const appTourOperatorsTourOperatorIdRouteRouteWithChildren =
  appTourOperatorsTourOperatorIdRouteRoute._addFileChildren(
    appTourOperatorsTourOperatorIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appTourOperatorsTourOperatorIdRouteRoute: typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  appTourOperatorsNewRoute: typeof appTourOperatorsNewRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appTourOperatorsTourOperatorIdRouteRoute:
    appTourOperatorsTourOperatorIdRouteRouteWithChildren,
  appTourOperatorsNewRoute: appTourOperatorsNewRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
