/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as appTourOperatorsTourOperatorIdRouteRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/route'
import { Route as appTourOperatorsNewRouteImport } from './routes/(app)/tour-operators/new'
import { Route as appTourOperatorsTourOperatorIdIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/index'
import { Route as appTourOperatorsTourOperatorIdExperiencesIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/index'
import { Route as appTourOperatorsTourOperatorIdExperiencesExperienceIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/experiences/$experienceId'
import { Route as appTourOperatorsTourOperatorIdSettingsIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/index'
import { Route as appTourOperatorsTourOperatorIdContentMediaIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/content/media/index'
import { Route as appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
import { Route as appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/general/index'
import { Route as appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/invitations/index'
import { Route as appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/index'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
import { Route as appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport } from './routes/(app)/tour-operators/$tourOperatorId/settings/members/new'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const appTourOperatorsTourOperatorIdRouteRoute =
  appTourOperatorsTourOperatorIdRouteRouteImport.update({
    id: '/tour-operators/$tourOperatorId',
    path: '/tour-operators/$tourOperatorId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appTourOperatorsNewRoute = appTourOperatorsNewRouteImport.update({
  id: '/tour-operators/new',
  path: '/tour-operators/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appTourOperatorsTourOperatorIdIndexRoute =
  appTourOperatorsTourOperatorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesIndexRoute =
  appTourOperatorsTourOperatorIdExperiencesIndexRouteImport.update({
    id: '/experiences/',
    path: '/experiences/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute =
  appTourOperatorsTourOperatorIdExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsIndexRoute =
  appTourOperatorsTourOperatorIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdContentMediaIndexRoute =
  appTourOperatorsTourOperatorIdContentMediaIndexRouteImport.update({
    id: '/content/media/',
    path: '/content/media/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdContentMediaMediaIdRoute =
  appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport.update({
    id: '/content/media/$mediaId',
    path: '/content/media/$mediaId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute =
  appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport.update({
    id: '/settings/general/',
    path: '/settings/general/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute =
  appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport.update({
    id: '/settings/invitations/',
    path: '/settings/invitations/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute =
  appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport.update(
    {
      id: '/settings/invitations/$invitationId',
      path: '/settings/invitations/$invitationId',
      getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
    } as any,
  )
const appTourOperatorsTourOperatorIdSettingsMembersIndexRoute =
  appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute =
  appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport.update({
    id: '/settings/members/$userId',
    path: '/settings/members/$userId',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)
const appTourOperatorsTourOperatorIdSettingsMembersNewRoute =
  appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport.update({
    id: '/settings/members/new',
    path: '/settings/members/new',
    getParentRoute: () => appTourOperatorsTourOperatorIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof appIndexRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute
  '/tour-operators/$tourOperatorId/experiences/': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/tour-operators/$tourOperatorId/settings/': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/tour-operators/$tourOperatorId/content/media/': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/tour-operators/$tourOperatorId/settings/general/': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/tour-operators/$tourOperatorId/settings/invitations/': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/tour-operators/$tourOperatorId/settings/members/': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof appIndexRoute
  '/tour-operators/new': typeof appTourOperatorsNewRoute
  '/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/tour-operators/$tourOperatorId/experiences/$experienceId': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute
  '/tour-operators/$tourOperatorId/experiences': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/tour-operators/$tourOperatorId/settings': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/tour-operators/$tourOperatorId/content/media': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/tour-operators/$tourOperatorId/settings/general': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/tour-operators/$tourOperatorId/settings/invitations': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/tour-operators/$tourOperatorId/settings/members': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/tour-operators/$tourOperatorId': typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  '/(app)/tour-operators/new': typeof appTourOperatorsNewRoute
  '/(app)/tour-operators/$tourOperatorId/': typeof appTourOperatorsTourOperatorIdIndexRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId': typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute
  '/(app)/tour-operators/$tourOperatorId/experiences/': typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/': typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId': typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId': typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/$userId': typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/new': typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  '/(app)/tour-operators/$tourOperatorId/content/media/': typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/general/': typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/invitations/': typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  '/(app)/tour-operators/$tourOperatorId/settings/members/': typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/invitations/accept'
    | '/'
    | '/tour-operators/$tourOperatorId'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId/'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId'
    | '/tour-operators/$tourOperatorId/experiences/'
    | '/tour-operators/$tourOperatorId/settings/'
    | '/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/tour-operators/$tourOperatorId/settings/members/new'
    | '/tour-operators/$tourOperatorId/content/media/'
    | '/tour-operators/$tourOperatorId/settings/general/'
    | '/tour-operators/$tourOperatorId/settings/invitations/'
    | '/tour-operators/$tourOperatorId/settings/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/invitations/accept'
    | '/'
    | '/tour-operators/new'
    | '/tour-operators/$tourOperatorId'
    | '/tour-operators/$tourOperatorId/experiences/$experienceId'
    | '/tour-operators/$tourOperatorId/experiences'
    | '/tour-operators/$tourOperatorId/settings'
    | '/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/tour-operators/$tourOperatorId/settings/members/new'
    | '/tour-operators/$tourOperatorId/content/media'
    | '/tour-operators/$tourOperatorId/settings/general'
    | '/tour-operators/$tourOperatorId/settings/invitations'
    | '/tour-operators/$tourOperatorId/settings/members'
  id:
    | '__root__'
    | '/(app)'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/invitations/accept'
    | '/(app)/'
    | '/(app)/tour-operators/$tourOperatorId'
    | '/(app)/tour-operators/new'
    | '/(app)/tour-operators/$tourOperatorId/'
    | '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId'
    | '/(app)/tour-operators/$tourOperatorId/experiences/'
    | '/(app)/tour-operators/$tourOperatorId/settings/'
    | '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
    | '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/new'
    | '/(app)/tour-operators/$tourOperatorId/content/media/'
    | '/(app)/tour-operators/$tourOperatorId/settings/general/'
    | '/(app)/tour-operators/$tourOperatorId/settings/invitations/'
    | '/(app)/tour-operators/$tourOperatorId/settings/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/tour-operators/$tourOperatorId': {
      id: '/(app)/tour-operators/$tourOperatorId'
      path: '/tour-operators/$tourOperatorId'
      fullPath: '/tour-operators/$tourOperatorId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/new': {
      id: '/(app)/tour-operators/new'
      path: '/tour-operators/new'
      fullPath: '/tour-operators/new'
      preLoaderRoute: typeof appTourOperatorsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/': {
      id: '/(app)/tour-operators/$tourOperatorId/'
      path: '/'
      fullPath: '/tour-operators/$tourOperatorId/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/'
      path: '/experiences'
      fullPath: '/tour-operators/$tourOperatorId/experiences/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId': {
      id: '/(app)/tour-operators/$tourOperatorId/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/tour-operators/$tourOperatorId/experiences/$experienceId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/'
      path: '/settings'
      fullPath: '/tour-operators/$tourOperatorId/settings/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/content/media/': {
      id: '/(app)/tour-operators/$tourOperatorId/content/media/'
      path: '/content/media'
      fullPath: '/tour-operators/$tourOperatorId/content/media/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdContentMediaIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId': {
      id: '/(app)/tour-operators/$tourOperatorId/content/media/$mediaId'
      path: '/content/media/$mediaId'
      fullPath: '/tour-operators/$tourOperatorId/content/media/$mediaId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/general/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/general/'
      path: '/settings/general'
      fullPath: '/tour-operators/$tourOperatorId/settings/general/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/invitations/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/invitations/'
      path: '/settings/invitations'
      fullPath: '/tour-operators/$tourOperatorId/settings/invitations/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
      path: '/settings/invitations/$invitationId'
      fullPath: '/tour-operators/$tourOperatorId/settings/invitations/$invitationId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/'
      path: '/settings/members'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/$userId': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/$userId'
      path: '/settings/members/$userId'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/$userId'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
    '/(app)/tour-operators/$tourOperatorId/settings/members/new': {
      id: '/(app)/tour-operators/$tourOperatorId/settings/members/new'
      path: '/settings/members/new'
      fullPath: '/tour-operators/$tourOperatorId/settings/members/new'
      preLoaderRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersNewRouteImport
      parentRoute: typeof appTourOperatorsTourOperatorIdRouteRoute
    }
  }
}

interface appTourOperatorsTourOperatorIdRouteRouteChildren {
  appTourOperatorsTourOperatorIdIndexRoute: typeof appTourOperatorsTourOperatorIdIndexRoute
  appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute: typeof appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute
  appTourOperatorsTourOperatorIdExperiencesIndexRoute: typeof appTourOperatorsTourOperatorIdExperiencesIndexRoute
  appTourOperatorsTourOperatorIdSettingsIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsIndexRoute
  appTourOperatorsTourOperatorIdContentMediaMediaIdRoute: typeof appTourOperatorsTourOperatorIdContentMediaMediaIdRoute
  appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute
  appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute
  appTourOperatorsTourOperatorIdSettingsMembersNewRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersNewRoute
  appTourOperatorsTourOperatorIdContentMediaIndexRoute: typeof appTourOperatorsTourOperatorIdContentMediaIndexRoute
  appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute
  appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute
  appTourOperatorsTourOperatorIdSettingsMembersIndexRoute: typeof appTourOperatorsTourOperatorIdSettingsMembersIndexRoute
}

const appTourOperatorsTourOperatorIdRouteRouteChildren: appTourOperatorsTourOperatorIdRouteRouteChildren =
  {
    appTourOperatorsTourOperatorIdIndexRoute:
      appTourOperatorsTourOperatorIdIndexRoute,
    appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute:
      appTourOperatorsTourOperatorIdExperiencesExperienceIdRoute,
    appTourOperatorsTourOperatorIdExperiencesIndexRoute:
      appTourOperatorsTourOperatorIdExperiencesIndexRoute,
    appTourOperatorsTourOperatorIdSettingsIndexRoute:
      appTourOperatorsTourOperatorIdSettingsIndexRoute,
    appTourOperatorsTourOperatorIdContentMediaMediaIdRoute:
      appTourOperatorsTourOperatorIdContentMediaMediaIdRoute,
    appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute:
      appTourOperatorsTourOperatorIdSettingsInvitationsInvitationIdRoute,
    appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute:
      appTourOperatorsTourOperatorIdSettingsMembersUserIdRoute,
    appTourOperatorsTourOperatorIdSettingsMembersNewRoute:
      appTourOperatorsTourOperatorIdSettingsMembersNewRoute,
    appTourOperatorsTourOperatorIdContentMediaIndexRoute:
      appTourOperatorsTourOperatorIdContentMediaIndexRoute,
    appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute:
      appTourOperatorsTourOperatorIdSettingsGeneralIndexRoute,
    appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute:
      appTourOperatorsTourOperatorIdSettingsInvitationsIndexRoute,
    appTourOperatorsTourOperatorIdSettingsMembersIndexRoute:
      appTourOperatorsTourOperatorIdSettingsMembersIndexRoute,
  }

const appTourOperatorsTourOperatorIdRouteRouteWithChildren =
  appTourOperatorsTourOperatorIdRouteRoute._addFileChildren(
    appTourOperatorsTourOperatorIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appTourOperatorsTourOperatorIdRouteRoute: typeof appTourOperatorsTourOperatorIdRouteRouteWithChildren
  appTourOperatorsNewRoute: typeof appTourOperatorsNewRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appTourOperatorsTourOperatorIdRouteRoute:
    appTourOperatorsTourOperatorIdRouteRouteWithChildren,
  appTourOperatorsNewRoute: appTourOperatorsNewRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
